# Single thermal zone reading.

std_msgs/Header header  # timestamp is the time the temperature was measured
                        # frame_id is the location of the thermal zone reading

# available_policies
# emul_temp
# integral_cutoff
# k_d
# k_i
# k_po
# k_pu
# mode
# offset
# policy
# power/
# slope
# subsystem/
# sustainable_power
# temp
sensor_msgs/Temperature temperature
# trip_point_0_hyst
# trip_point_0_temp
# trip_point_1_hyst
# trip_point_1_temp
# trip_point_1_type
# trip_point_2_hyst
# trip_point_2_temp
# trip_point_2_type
# type
string type
# uevent
# trip_point_0_type
